### ISSUE TITLE
'\t' in bam header

### ISSUE THREAD

**Issue by wangjiawen2013** [nccl-jmli/VarBen#12]
Hi,
when '\t' are included in bam header (for example, read group header line such as '@RG\tID:foo\tSM:bar'), VarBen will report errors and stop at the remapping stage. It seems that the python script cannot resolve the bam header correctly because '\t' is a non-literal characters.
Here are some related issues:
https://github.com/tseemann/snippy/issues/100
https://github.com/CPTR-ReSeqTB/UVP/issues/18

**Comment by yulijia** [comment]
Hi @wangjiawen2013 

Thank you for point out this problem.

I made an update on the `remap` function, please download the new source code and help me to test if it works on your local.

**Comment by wangjiawen2013** [comment]
It worked

**Comment by yulijia** [comment]
@wangjiawen2013  Thank you for your feedback!
