### ISSUE TITLE
can't add cnv variants

### ISSUE THREAD

**Issue by diushiguzhi** [nccl-jmli/VarBen#17]
Hi,

When I use your software to add cnv variants, there have error ：'could not convert string to float: cnv'.
Counld I use the software to add cnv variants ?

Looking forward to your reply!
Thanks

**Comment by yulijia** [comment]
I suppose that you have found the answer, right? 
Please read the readme page carefully.

**Comment by diushiguzhi** [comment]
Yes，I got it




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nccl-jmli/VarBen"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月8日(星期一) 下午3:27
收件人:&nbsp;"nccl-jmli/VarBen"<VarBen@noreply.github.com&gt;;
抄送:&nbsp;"丢失固执"<1060073538@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [nccl-jmli/VarBen] can't add cnv variants (#17)





 
I suppose that you have found the answer, right?
 Please read the readme page carefully.
