### ISSUE TITLE
 CIGAR and query sequence lengths difference

### ISSUE THREAD

**Issue by zhangyafeng1** [nccl-jmli/VarBen#18]
hi ，liliya:

when I run  "muteditor.py"  , the following error is reported :

`Exception: Cmd Error: samtools sort -n -o /bioinfo/home/tempDir/edit.sortByName.bam  /bioinfo/home/tempDir/edit.bam`

Then I run this command line , the error is : 
`[E::bam_read1] CIGAR and query sequence lengths differ for A00821:395:H7Y5MDSXY:3:2170:22788:14497
samtools sort: truncated file. Aborting`

I extracted this reads, when it is a hardclip reads , the reads will be trimed by BWA , So led to the error . 
I'm not sure if this is the reason, or is my script  problem?
![image](https://user-images.githubusercontent.com/52239895/110922750-0a1f0600-835b-11eb-9edb-cea74d773b9b.png)

Thank you !

**Comment by yulijia** [comment]
Hi,
If your input file contains `hardclip` reads (before Verben editing), please filtering it via `samtools view -b -F 0x100 a.bam > b.bam`.
If you still meet the same problem after filtering, please let us know.

**Comment by asmmahmoud** [comment]
Hi  Lijia Yu, 
I had same error and run the samtools command you provided above the run 'muteditor.py' again with the filtered bam file but got exactly same error at the same read. Could you help me? 

Thank you

**Comment by asmmahmoud** [comment]
Hi @zhangyafeng1 
If you still have the same issue, I fixed it with this command "samtools view -h original.bam | awk '$6 !~ /H/{print}' | samtools view -bS - > noHclips.bam". It removed all hardclip reads, then index the filtered bam file and run muteditor.py again. 
Hopefully it helps you :)

**Comment by yulijia** [comment]
@AsmaaSamyMohamedMahmoud  

Thank you for the helpful feedback!
