### ISSUE TITLE
TorrentServer pysam version not meeting the requirements

### ISSUE THREAD

**Issue by argoat** [nccl-jmli/VarBen#20]
Hi,

default version of pysam installed on TorrentServer was 0.7.7, while VarBen require pysam>=0.9.4. 
We failed to update pysam on TS5.4/5.6/5.10 since default library had been set to 'ion-updates' and cannot be changed.
Any suggestion?

Regards
Tang

**Comment by yulijia** [comment]
Sorry for the late reply, have you tried `conda` to create a python environment with `pysam>=0.9.4` ?
BTW, we suggest you install the VerBen on another server other than the TorrentServer.

**Comment by argoat** [comment]
Thanks. We tried both ( with docker ) and go with the latter one.
