### ISSUE TITLE
muteditor.py  CIGAR and query sequence lengths differ

### ISSUE THREAD

**Issue by kaixinxiaonvwa-hub** [nccl-jmli/VarBen#24]
Hi Lijia Yu,
When I was runningmuteditor.py script, the error CIGAR and query sequence lengths differ  happen 

python2 bin/muteditor.py -m /data/project/varben_model_20230209/test_l4/varben.tsv -b /data/project/varben_model_20230209/test_l4/n5TRUE.mem_pe.sort.bam -r /data/Homo_sapiens/Homo_sapiens_38/Homo_sapiens_assembly38.fasta -p 4 --aligner bwa --alignerIndex /data/Homo_sapiens/Homo_sapiens_38/Homo_sapiens_assembly38.fasta --seqer illumina --haplosize 10 --mindepth 500 --minmutreads 5 --snpfrac 0.1 --outdir /data/project/varben_model_20230209/test_l4/n5.50.sort.varben.snv_out
 
the error is 
samtools sort start................................
samtools sort -n -o /data/project/varben_model_20230209/test_l4/n5.50.sort.varben.snv_out/tempDir/edit.sortByName.bam /data/project/varben_model_20230209/test_l4/n5.50.sort.varben.snv_out/tempDir/edit.bam
[E::bam_read1] CIGAR and query sequence lengths differ for A00265:734:HK2CTDSX2:2:2424:27968:16360
samtools sort: truncated file. Aborting
Traceback (most recent call last):
  File "bin/muteditor.py", line 122, in <module>
    run()
  File "bin/muteditor.py", line 118, in run
    main(run_args)
  File "bin/muteditor.py", line 60, in main
    run_args.alignerIndex, run_args.single)
  File "/root/software/varben/VarBen-master/bin/../varben/deal_mut/readsReplace.py", line 65, in reads_replace
    remap(aligner_index, edit_bam_file, edit_remap_bam_file, aligner, is_single, header=head)
  File "/root/software/varben/VarBen-master/bin/../varben/common/bamconvert.py", line 98, in remap
    bamSort(inBamFile, inPrefix + ".sortByName", sort_key="name")
  File "/root/software/varben/VarBen-master/bin/../varben/common/bamconvert.py", line 78, in bamSort
    _call(bamSort_cmd)
  File "/root/software/varben/VarBen-master/bin/../varben/common/bamconvert.py", line 14, in _call
    raise Exception("Cmd Error: %s" % cmd)
Exception: Cmd Error: samtools sort -n -o /data/project/varben_model_20230209/test_l4/n5.50.sort.varben.snv_out/tempDir/edit.sortByName.bam /data/project/varben_model_20230209/test_l4/n5.50.sort.varben.snv_out/tempDir/edit.bam

I have use picard.jar ValidateSamFile to find where the error is ,but the software say "No errors found"

Could you help me fix it ?

**Comment by kaixinxiaonvwa-hub** [comment]
I have solve the problem with samtools view -b -F 0x100 a.bam > b.bam 
the link is
https://github.com/nccl-jmli/VarBen/issues/18

**Comment by yulijia** [comment]
Thank you for your feedback, I will highlight the solution of these issues in the README file
