### ISSUE TITLE
CNV input format

### ISSUE THREAD

**Issue by Gerde** [nccl-jmli/VarBen#6]
Dear Prof. Li,
      I got some error message when simulating CNV use VarBen, could you please help me ?
      the command:
      `python VarBen-master/bin/sveditor.py --svfile mut.list --bamfile mybam.bam --reffasta hg19.fasta --readlength 150 -o varben_out --alignerIndex hg19.fasta --seqer illumina --aligner bwa`
      the input sv file:
`chr1    110883028       110884090       cnv     2.5     gain`
`chr1    16258586        16259761        cnv     2       loss`
      and I got these error:
`['chr1', '110883028', '110884090', 'cnv', '2.5', 'gain']`
`['chr1', '16258586', '16259761', 'cnv', '2', 'loss']`
`Traceback (most recent call last):
  File "/mnt/cfs/project/test_freshman/liaoxinhui/3.20190624_bio_performance/software/VarBen-master/bin/../varben/deal_sv/checkSVInput.py", line 40, in check_sv
    raise Exception("cnv is not in correct format")
Exception: cnv is not in correct format
`
`('cnv is not in correct format',)
('chr1\t16258586\t16259761\tcnv\t2\tloss', 'cnv is not in correct format')
`
    It seems that the 'AF' column in input file is uncorrected, so how to set 'AF' column ? Was the 'AF' column mean copies of gain/loss ?
    Thanks a lot!
Best,
Gerde Liao

**Comment by yulijia** [comment]
Hi Gerde,

As shown in the source code, https://github.com/nccl-jmli/VarBen/blob/master/varben/deal_sv/checkSVInput.py#L36

The copy number of CNV for loss type is less or equal to 1. 

Thank you for contacting us, we will fix the wrong description in the README file.

**Comment by Gerde** [comment]
Hi lijia,

      Thanks for your reply !
      So the 'AF' represent the 'copy ratio', am I right ?
      And I have another question here, what's the difference between 'dup/del' and 'gain/loss' in SV simualtion ?
      Thanks much!
Best,
Gerde

**Comment by yulijia** [comment]
Hi Gerde,

Yes, 'AF' represents to 'copy ratio'.

At here, we introduce a type of simple CNV, when modifying the BAM file, we don't create any 'breakpoint' at the start and end site. That means we just add or reduce the read depth of the target region.  

Best,
Lijia

**Comment by Gerde** [comment]
Hi lijia,

Thanks a lot! It is much more clear for me now.
VarBen is an efficiency variant simulation tool, thanks for your developments.
I will close this issue.

Best,
Gerde
